"""
The sequence you're referencing is known as the "Look-and-say" sequence. Each term is generated by describing the previous term. Here’s how it works:
Starting with "1":
The next term describes "1": "one 1" → "11"
The next term describes "11": "two 1s" → "21"
The next term describes "21": "one 2, then one 1" → "1211"
The next term describes "1211": "one 1, one 2, two 1s" → "111221"
The next term describes "111221": "three 1s, two 2s, one 1" → "312211"
Let's generate the next term after "312211" using a Python function:
"""


def next_look_and_say (term):
    result = []
    i = 0
    while i < len (term):
        count = 1
        while i + 1 < len (term) and term[i] == term[i + 1]:
            i += 1
            count += 1
        result.append (f"{count}{term[i]}")
        i += 1
    return ''.join (result)


# Given term in the sequence
current_term = str (1)
for i in range (2, 10):
    next_term = next_look_and_say (current_term)
    print (next_term, end=" ")
    current_term = next_term
