DELETE FROM soorten;

INSERT INTO soorten (SoortNr, Soort) VALUES (2, 'Alcoholarm');
INSERT INTO soorten (SoortNr, Soort) VALUES (3, 'Alcoholvrij');
INSERT INTO soorten (SoortNr, Soort) VALUES (4, 'Ale');
INSERT INTO soorten (SoortNr, Soort) VALUES (5, 'Alt');
INSERT INTO soorten (SoortNr, Soort) VALUES (6, 'Amber');
INSERT INTO soorten (SoortNr, Soort) VALUES (8, 'Bierette');
INSERT INTO soorten (SoortNr, Soort) VALUES (11, 'Bitter');
INSERT INTO soorten (SoortNr, Soort) VALUES (12, 'Donkerbok');
INSERT INTO soorten (SoortNr, Soort) VALUES (13, 'Dort');
INSERT INTO soorten (SoortNr, Soort) VALUES (14, 'Dubbel Donker');
INSERT INTO soorten (SoortNr, Soort) VALUES (15, 'Edelbier');
INSERT INTO soorten (SoortNr, Soort) VALUES (18, 'Extra');
INSERT INTO soorten (SoortNr, Soort) VALUES (19, 'Faro');
INSERT INTO soorten (SoortNr, Soort) VALUES (21, 'Gerstewijn');
INSERT INTO soorten (SoortNr, Soort) VALUES (22, 'Geuze');
INSERT INTO soorten (SoortNr, Soort) VALUES (25, 'Helderbok');
INSERT INTO soorten (SoortNr, Soort) VALUES (26, 'IJsbier');
INSERT INTO soorten (SoortNr, Soort) VALUES (31, 'Lambik');
INSERT INTO soorten (SoortNr, Soort) VALUES (33, 'Lichtblond');
INSERT INTO soorten (SoortNr, Soort) VALUES (34, 'Light');
INSERT INTO soorten (SoortNr, Soort) VALUES (35, 'Mars');
INSERT INTO soorten (SoortNr, Soort) VALUES (36, 'Massieve Ale');
INSERT INTO soorten (SoortNr, Soort) VALUES (42, 'Pils');
INSERT INTO soorten (SoortNr, Soort) VALUES (44, 'Rookbier');
INSERT INTO soorten (SoortNr, Soort) VALUES (45, 'Saison');
INSERT INTO soorten (SoortNr, Soort) VALUES (46, 'Scotch');
INSERT INTO soorten (SoortNr, Soort) VALUES (49, 'Stout');
INSERT INTO soorten (SoortNr, Soort) VALUES (51, 'Tafelbier');
INSERT INTO soorten (SoortNr, Soort) VALUES (53, 'Tarwebier of witbier');
INSERT INTO soorten (SoortNr, Soort) VALUES (54, 'Traditionele Faro');
INSERT INTO soorten (SoortNr, Soort) VALUES (55, 'Traditionele Geuze');
INSERT INTO soorten (SoortNr, Soort) VALUES (56, 'Traditionele Lambik');
INSERT INTO soorten (SoortNr, Soort) VALUES (59, 'Tripel');
INSERT INTO soorten (SoortNr, Soort) VALUES (60, 'Versnijbier');
INSERT INTO soorten (SoortNr, Soort) VALUES (61, 'Vlaams Bruin');
INSERT INTO soorten (SoortNr, Soort) VALUES (62, 'Vlaams Rood');
INSERT INTO soorten (SoortNr, Soort) VALUES (64, 'West-Vlaamse Geuze');
INSERT INTO soorten (SoortNr, Soort) VALUES (65, 'West-Vlaamse spontane Geuze');

SELECT * FROM soorten;