DELETE FROM brouwers;

INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (1, 'Achouffe', 'Route du Village 32', 6666, 'Achouffe-Wibrin', 10000);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (2, 'Alken', 'Stationstraat 2', 3570, 'Alken', 950000);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (3, 'Ambly', 'Rue Principale 45', 6953, 'Ambly-Nassogne', 500);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (4, 'Anker', 'Guido Gezellelaan 49', 2800, 'Mechelen', 3000);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (6, 'Artois', 'Vaartstraat 94', 3000, 'Leuven', 4000000);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (8, 'Bavik', 'Rijksweg 33', 8531, 'Bavikhove', 110000);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (9, 'Belle Vue - Molenbeek', 'Henegouwenkaai 33', 1080, 'Sint-Jans-Molenbeek', NULL);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (10, 'Belle Vue - Zuun', 'Steenweg naar Bergen', 1600, 'Sint- Pieters-Leeuw', NULL);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (11, 'Belle Vue', 'Delaunoy-straat 58-60', 1080, 'Sint-Jans-Molenbeek', 300000);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (12, 'Bie (De)', 'Stoppelweg 26', 8978, 'Watou', 280);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (13, 'Binchoise', 'Faubourg St. Paul 38', 7130, 'Binche', 700);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (14, 'Bios', 'Lindenlaan 25', 9940, 'Ertvelde', 40000);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (15, 'Blaugies', 'Rue de la Frontiere 435', 7370, 'Blaugies', 280);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (17, 'Bocq', 'Rue de la Brasserie 4', 5530, 'Purnode', 60000);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (18, 'Boelens', 'Kerkstraat 7', 9111, 'Belsele', 300);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (19, 'Boon', 'Fonteinstraat 65', 1502, 'Lembeek', 2350);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (20, 'Bosteels', 'Kerkstraat 92', 9255, 'Buggenhout', 50000);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (21, 'Brunehaut', 'Rue des Panneries 17', 7623, 'Brunehaut', 3800);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (22, 'Cantillon', 'Gheudestraat 56', 1070, 'Anderlecht', 850);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (23, 'Caracole', 'Cote Marie-Therese 86', 5500, 'Falmignoul', 350);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (24, 'Caulier', 'Rue Sondeveille 134', 7600, 'Peruwelz', 1500);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (25, 'Chimay', 'Rue de la Trappe 294', 6464, 'Forges-les-Chimay', 100000);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (26, 'Clarysse', 'Krekelput 16-18', 9700, 'Oudenaarde', 15000);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (27, 'Cnudde', 'Fabriekstraat 8', 9700, 'Eine', NULL);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (28, 'Contreras', 'Molenstraat 115', 9890, 'Gavere', 2000);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (29, 'Crombe', 'Hospitaalstraat 10', 9620, 'Zottegem', 1000);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (30, 'Deca', 'Elverdingestraat 4', 8640, 'Woesten-Vleteren', 10000);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (32, 'Dolle brouwers', 'Roeselarestraat 12b', 8600, 'Esen- Diksmuide', 1200);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (33, 'Domus', 'Tiensestraat 8', 3000, 'Leuven', 1000);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (34, 'Dool', 'Eikendreef 21', 3530, 'Helchteren', 1500);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (35, 'Drie Fonteinen', 'H. Teirlinckplein 3', 1650, 'Beersel', 180);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (36, 'Dubuisson', 'Chaussee de Mons 28', 7904, 'Pipaix', 15840);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (37, 'Dupont', 'Rue Basse 5', 7904, 'Tourpes-Leuze', 6000);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (38, 'Duwac', 'Rue des Rossignols 20', 7700, 'Mouscron', 900);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (39, 'Duysters', 'Michel Theysstraat 58 a', 3290, 'Diest', NULL);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (40, 'Ellezelloise', 'Guinaumont 75', 7890, 'Ellezelles', 1000);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (41, 'Eupener', 'Paveestrasse 12-14', 4700, 'Eupen', 20000);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (42, 'Eylenbosch - Maes', 'Ninoofsesteenweg 5', 1703, 'Schepdaal', 12000);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (43, 'Facon', 'Kwabrugstraat 27', 8510, 'Bellegem', 8000);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (44, 'Fantome', 'Rue Preal 8', 6997, 'Soy', 900);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (45, 'Ferme au Chene', 'Rue Comte d''Ursel 36', 6940, 'Durbuy', 100);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (46, 'Friart', 'Rue d'' Houdeng 20', 7070, 'Le Roeulx', 18000);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (47, 'Gaverhopke', 'Steenbrugstraat 187', 8530, 'Harelbeke- Stasegem', 800);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (48, 'Gigi', 'Grand rue 96', 6769, 'Gerouville', 4000);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (49, 'Girardin', 'Lindenberg 10', 1700, 'Sint-Ulriks-Kapelle', 3900);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (50, 'Gouden Boom', 'Langestraat 45', 8000, 'Brugge', 20000);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (51, 'Haacht', 'Provinciesteenweg 28', 3190, 'Boortmeerbeek', 1100000);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (53, 'Hanssens', 'Vroenenbosstraat 15', 1653, 'Dworp', 500);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (54, 'Hopduvel', 'Coupure links 625', 9000, 'Gent', 550);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (55, 'Hopperd', 'Matestraat 7', 2230, 'Ramsel', NULL);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (56, 'Huyghe', 'Brusselsesteenweg 282', 9090, 'Melle', 50000);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (57, 'John Martin', 'Rue du Cerf 191', 1332, 'Genval', NULL);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (58, 'Jupiler', 'Rue de Vise 243', 4020, 'Jupille-sur-Meuse', 2200000);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (59, 'K.I.H.O.', 'Gebroeders de Smetstraat 1', 9000, 'Gent', NULL);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (60, 'Keersmaeker (De)', 'Lierput 1', 1730, 'Kobbegem', 60000);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (62, 'Koninck - Antwerpen (De)', 'Mechelsesteenweg 291', 2018, 'Antwerpen', 140000);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (64, 'Lefebvre', 'Rue de Croly 54', 1430, 'Quenast', 15000);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (65, 'Leroy', 'Diksmuideseweg 406', 8904, 'Boezinge', 32000);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (66, 'Liefmans', 'Aalststraat 200', 9700, 'Oudenaarde', 10000);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (67, 'Lindemans', 'Lenniksebaan 1479', 1602, 'Vlezenbeek', 19000);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (68, 'Louwaege', 'Markt 14', 8610, 'Kortemark', 22000);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (69, 'Maes', 'Waarloosveld 10', 2550, 'Waarloos', 1150000);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (70, 'Martens', 'Reppelerweg 1', 3950, 'Bocholt', 600000);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (71, 'Meesters', 'Hoogstraat 50', 1570, 'Galmaarden', 160);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (72, 'Mibrana', 'Place de la station 2', 5000, 'Namur', 380);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (73, 'Miroir', 'Koningin Astridplein 24-26', 1090, 'Jette', 100);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (74, 'Moortgat', 'Breendonkdorp 58', 2870, 'Breendonk-Puurs', 250000);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (75, 'Old Bailey', 'Kerkplein 5', 8880, 'St.-Eloois-Winkel', 1200);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (76, 'Oleye', 'Rue d''Elmette 39', 4300, 'Oleye-Waremme', 200);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (78, 'Orval', 'Orval 2', 6823, 'Villers-devant-Orval', 37000);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (79, 'Paeleman', 'Boekakker 1', 9230, 'Wetteren', 350);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (80, 'Pakhuis', 'Vlaamse kaai 76', 2000, 'Antwerpen', 1200);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (81, 'Palm', 'Steenhuffeldorp 3', 1840, 'Steenhuffel', 530000);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (82, 'Pater Van Damme', 'Jacob Van Maerlantstraat 2', 8340, 'Damme', 7);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (83, 'Praile', 'Rue de la Praile 3', 7120, 'Peissant', 24);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (84, 'Proefbrouwerij', 'Smalle Heerweg 78', 9080, 'Lochristi', 500);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (85, 'Ranke', 'Brugstraat 43', 8560, 'Wevelgem', 100);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (86, 'Regenboog', 'Astridlaan 134', 8310, 'Assebroek-Brugge', NULL);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (87, 'Riva', 'Wontergemstraat 42', 8720, 'Dentergem', 115000);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (88, 'Roberg', 'Rodebergstraat 46', 8954, 'Westouter', 1000);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (89, 'Rochefort', 'Rue de l''abbaye 8', 5580, 'Rochefort', 15000);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (90, 'Rochefortoise', 'Rue du Treux 43b', 5580, 'Eprave', NULL);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (91, 'Rocs', 'Chaussee Brunehaut 37', 7387, 'Montignies-sur-Roc', 500);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (92, 'Rodenbach', 'Spanjestraat 133', 8800, 'Roeselare', 150000);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (93, 'Roman', 'Hauwaert 61', 9700, 'Oudenaarde-Mater', 100000);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (94, 'Ruwet', 'Rue Victor Besme 27', 4800, 'Verviers', 100);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (95, 'Ryck (De)', 'Kerkstraat 28', 9550, 'Herzele', 6000);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (96, 'Schuur', 'Gobbelsrode 75', 3220, 'Kortrijk-Dutsel', NULL);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (97, 'Silenrieux', 'Rue Noupre 1', 5630, 'Silenrieux', 500);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (98, 'Silly', 'Ville Basse A 141', 7830, 'Silly', 12000);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (99, 'Slaghmuylder', 'Denderhoutembaan 2', 9400, 'Ninove', 6500);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (100, 'Smedt (De)', 'Ringlaan 18', 1745, 'Opwijk', 50000);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (101, 'St. Bernardus', 'Trappistenweg 23', 8978, 'Watou', 13000);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (102, 'St. Guibert', 'Rue de Riquau 1', 1435, 'Mont-Saint-Guibert', 350000);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (103, 'St. Jozef', 'Itterplein 19', 3960, 'Opitter', 65000);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (104, 'Steedje', 'Schoolstraat 45b', 8460, 'Ettelgem', 1000);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (105, 'Sterkens', 'Meerdorp 20', 2321, 'Meer', 8613);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (106, 'Straffe Hendrik', 'Walplein 26', 8000, 'Brugge', 5800);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (107, 'Strubbe', 'Markt 1', 8480, 'Ichtegem', 20000);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (108, 'Timmermans', 'Kerkstraat 11', 1701, 'Itterbeek', 10000);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (109, 'Tour', 'Rue Chera 9', 4180, 'Comblain-la-Tour', 240);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (110, 'Troch (De)', 'Langestraat 20', 1741, 'Ternat-Wambeek', 3500);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (111, 'Union', 'Rue Derbeque 7', 6040, 'Jumet', 200000);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (112, 'Van Den Bossche', 'Sint-Lievensplein 16', 9550, 'Sint- Lievens-Esse', 1700);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (113, 'Van Eecke', 'Douvieweg 2', 8978, 'Watou', 10000);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (114, 'Van Honsebrouck', 'Oostrozebekestraat 43', 8770, 'Ingelmunster', 80000);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (115, 'Vander Linden', 'Brouwerijstraat 2', 1500, 'Halle', 2000);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (116, 'Vandervelden Henri', 'Laarheidestraat 230', 1650, 'Beersel', 500);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (117, 'Vapeur', 'Rue de Marechal 1', 7904, 'Pipaix-Leuze', 1000);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (118, 'Verhaeghe', 'Beukenhofstraat 96', 8570, 'Vichte', 7200);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (119, 'Vervifontaine', 'xxx', 0, 'Fontaine-Jalhay', NULL);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (120, 'Villers', 'Liezeledorp 37', 2870, 'Liezele-Puurs', 1450);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (121, 'Walrave', 'Lepelstraat 36', 9270, 'Laarne', 2500);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (122, 'Weldebroec', 'Mechelse Steenweg 53', 2830, 'Willebroek', 800);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (123, 'Westmalle', 'Antwerpsesteenweg 496', 2390, 'Malle', 125000);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (124, 'Westvleteren', 'Donkerstraat 12', 8640, 'Westvleteren', 4000);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (125, 'Wieze', 'Nieuwstraat 1', 9280, 'Wieze', 120000);
INSERT INTO brouwers (BrouwerNr, BrouwerNaam, Adres, PostCode, Gemeente, Omzet) VALUES (126, 'Zwingel', 'Damweg 6', 8530, 'Harelbeke', 250);


SELECT * FROM brouwers